name: demandium
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.3+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: #^4.7.2
    git:
      url: https://github.com/luis901101/getx_fork.git
      ref: old-4.7.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  path_provider: ^2.1.5
  url_strategy: ^0.3.0
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  country_code_picker: ^3.4.1
  phone_numbers_parser: ^9.0.15
  webview_flutter: ^4.13.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html_core: ^0.17.0
  flutter_typeahead: ^5.2.0
  pointer_interceptor: ^0.10.1+2
  shimmer_animation: ^2.2.2
  carousel_slider: ^5.1.1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  smooth_page_indicator: ^1.2.1
  expandable: ^5.0.1
  file_picker: ^10.3.3
  flutter_html: ^3.0.0
  flutter_local_notifications: ^19.5.0
  universal_html: ^2.2.4
  flutter_inappwebview: ^6.1.5
  timeago: ^3.7.1
  pdf: ^3.11.3
  diffutil_dart: ^4.0.1
  flutter_downloader: ^1.12.0
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  printing: ^5.14.2
  audioplayers: ^6.5.1
  dotted_border: ^3.1.0
  expandable_bottom_sheet: ^1.1.1+1
  share_plus: ^12.0.1
  rect_getter: ^1.1.0
  scroll_to_index: any
  http_parser: ^4.1.2
  http: ^1.5.0
  path: ^1.9.1
  syncfusion_flutter_datepicker: ^31.2.4
  sign_in_with_apple: ^7.0.1
  uuid: ^4.5.1
  just_the_tooltip: ^0.0.12
  custom_info_window: ^1.0.1
  custom_marker: ^1.0.0
  photo_view: ^0.15.0
  flutter_slidable: ^4.0.3
  app_links: ^6.4.1
  syncfusion_flutter_sliders: ^31.2.4
  syncfusion_flutter_core: ^31.2.4
  flutter_xlider: ^3.5.0
  video_player: ^2.10.0
  chewie: ^1.13.0
  firebase_auth: ^6.1.1
  readmore: ^3.0.0
  lottie: ^3.3.2
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  skeletonizer: ^2.1.0+1
  app_tracking_transparency: ^2.0.6+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/json/
    - assets/map/
    - assets/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
